[package]
name = "cppmm-build"
version = "0.3.0"
edition = "2018"
description="Build utilities for cppmm-based projects"
license="BSD-3-Clause"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]


[dependencies]
cmake = "^0.1"
regex = "^1.5"
quick-xml = "^0.22"
